### ISSUE TITLE
image-rs failing to pull "quay.io/opendatahub/caikit-tgis-serving@sha256:794adc22d52cb3ac4b5aadfb286e8431cca829acdc4909719329cf8c4fabb4ec

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/guest-components#378]
Error from kata-agent received
```
{"msg":"pull and unpack image \"quay.io/opendatahub/caikit-tgis-serving@sha256:794adc22d52cb3ac4b5aadfb286e8431cca829acdc4909719329cf8c4fabb4ec\", cid: \"5a1ef1382aff765c8778051da2cf054bfca0b9ce587cb4eba3ce5375fc26d3d1\", with image-rs failed with \"failed to handle layer: hasher sha256: failed to unpack `/run/image/layers/sha256_32ad89a311d48e8bc1ba4bb05b1eedf2039cadb01c67494ee6c4c8a3e1e7931a/opt/miniconda/pkgs/boltons-23.0.0-py39h06a4308_0/lib/python3.9/site-packages/boltons-23.0.0.dist-info/INSTALLER`\\n\\nCaused by:\\n    No such file or directory (os error 2) while canonicalizing 
```
Ran the test `test_pull_image` with the image, and following is the trace output:
```
---- image::tests::test_pull_image stdout ----
Got error on function call attempt 0. Will retry in 1s: failed to handle layer: hasher sha256: channel: read failed Custom { kind: Other, error: reqwest::Error { kind: Body, source: hyper::Error(Body, Error { kind: Reset(StreamId(11), INTERNAL_ERROR, Remote) }) } }
Got error on function call attempt 1. Will retry in 1s: failed to handle layer: hasher sha256: channel: read failed Custom { kind: Other, error: reqwest::Error { kind: Body, source: hyper::Error(Body, Error { kind: Reset(StreamId(11), PROTOCOL_ERROR, Remote) }) } }
Got error on function call attempt 2. Will retry in 1s: failed to handle layer: hasher sha256: channel: read failed Custom { kind: Other, error: reqwest::Error { kind: Body, source: hyper::Error(Body, Error { kind: Reset(StreamId(11), INTERNAL_ERROR, Remote) }) } }
Got error on function call attempt 3. Will retry in 1s: failed to handle layer: hasher sha256: channel: read failed Custom { kind: Other, error: reqwest::Error { kind: Body, source: hyper::Error(Body, Error { kind: Reset(StreamId(11), PROTOCOL_ERROR, Remote) }) } }
Got error on function call attempt 4. Will retry in 1s: failed to handle layer: hasher sha256: channel: read failed Custom { kind: Other, error: reqwest::Error { kind: Body, source: hyper::Error(Body, Error { kind: Reset(StreamId(11), PROTOCOL_ERROR, Remote) }) } }
thread 'image::tests::test_pull_image' panicked at 'Function did not return Ok after retries: last_err Some(failed to handle layer: hasher sha256: channel: read failed Custom { kind: Other, error: reqwest::Error { kind: Body, source: hyper::Error(Body, Error { kind: Reset(StreamId(11), PROTOCOL_ERROR, Remote) }) } })', image-rs/src/image.rs:542:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: image_rs::image::tests::test_pull_image::{{closure}}
             at ./src/image.rs:542:13
   3: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/future/future.rs:125:9
   4: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/future/future.rs:125:9
   5: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/current_thread/mod.rs:665:57
   6: tokio::runtime::coop::with_budget
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
   7: tokio::runtime::coop::budget
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
```

**Comment by bpradipt** [comment]
cc @arronwy @Xynnn007

**Comment by ChengyuZhu6** [comment]
@bpradipt Insufficient memory may cause this error.

**Comment by bpradipt** [comment]
> @bpradipt Insufficient guest memory may cause this error.

That was our first guest, but memory was significant in the environment. Also creating a new image worked. So something specific with handling of this image.

**Comment by Xynnn007** [comment]
This can be pulled w/o error now. I just test locally
