### ISSUE TITLE
CDH: credentials should be optional in the configuration toml

### ISSUE THREAD

**Issue by wainersm** [confidential-containers/guest-components#514]
I'm trying to launch cdh configured for `offline_fs_kbc` where I don't want to load any credentials but I'm getting `missing field \`credentials\`` errors.

Here is the configuration file and execution output:

```shell
$ cat cdh_conf.toml 
socket = "unix:///run/confidential-containers/cdh.sock"

[kbc]
name = "offline_fs_kbc"
url = ""
kbs_cert = ""
$ sudo ../target/x86_64-unknown-linux-gnu/release/confidential-data-hub -c cdh_conf.toml &
[4] 1053939
$ [2024-03-21T15:03:07Z INFO  confidential_data_hub] Use configuration file cdh_conf.toml
thread 'main' panicked at confidential-data-hub/hub/src/bin/confidential-data-hub/config.rs:79:65:
called `Result::unwrap()` on an `Err` value: invalid config

Caused by:
    missing field `credentials`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Then I added an empty `[credentials]` section to the toml file and got another error:
```shell
$ cat cdh_conf.toml
socket = "unix:///run/confidential-containers/cdh.sock"

[kbc]
name = "offline_fs_kbc"
url = ""
kbs_cert = ""

[credentials]
$ sudo ../target/x86_64-unknown-linux-gnu/release/confidential-data-hub -c cdh_conf.toml &
[4] 1054383
$ [2024-03-21T15:06:52Z INFO  confidential_data_hub] Use configuration file cdh_conf.toml
thread 'main' panicked at confidential-data-hub/hub/src/bin/confidential-data-hub/config.rs:79:65:
called `Result::unwrap()` on an `Err` value: invalid config

Caused by:
    invalid type: map, expected a sequence
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Alright, an empty `[[credentials]]` didn't work either because now it requires `resource_uri` and `path`...

**Comment by Xynnn007** [comment]
Hi @wainersm TOML crate seems not intelligent enough to handle empty arrays thus I explicitly fix that in a PR.

BTW, `[[credentials]]` items should have double square brackets rather than single.
